//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hareketler
    {
        public byte ID { get; set; }
        public Nullable<byte> Kitap { get; set; }
        public Nullable<byte> Uye { get; set; }
        public Nullable<byte> Personel { get; set; }
        public Nullable<System.DateTime> AlisTarih { get; set; }
        public Nullable<System.DateTime> IadeTarih { get; set; }
        public Nullable<System.DateTime> UyeGetirdigiTarih { get; set; }
        public Nullable<bool> IslemDurum { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
